services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8181:8181

  web:
    build:
      context: ./web/dice-game
      dockerfile: Dockerfile
    ports:
      - 3000:3000
