services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 81818:81818

  web:
    build:
      context: ./web/dice-game
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./web/dice-game:/app
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:81818
    depends_on:
      - api
